#!/bin/sh

# Aquest script mostra la xuleta de cheatsheets seleccionada a partir del llistat de dmenu

QUERY="$(/usr/bin/ls $HOME/.local/repos/cheatsheets/*.md | awk -F"[/.]" '{print $8}' | dmenu -i -l 30)"

if [ -n "$QUERY" ]; then
	$BROWSER "https://devhints.io/""$QUERY"
fi
