#!/usr/bin/env bash
#
# Nom de l'script: dmconf
# Descripció: per editar d'un llista d'arxius de configuració.
# Dependències: dmenu
# Llicència: https://www.github.com/enricg/scripts/LICENSE
# Contributors: Derek Taylor
# Author: Derek Taylor

# Defining the text editor to use.
DMENUEDITOR="st -e $EDITOR"

# An array of options to choose.
# You can edit this list to add/remove config files.
source ~/.local/bin/items/dmconfItems

# Piping the above array into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l 20 -p 'Edit config:')

# What to do when/if we choose 'quit'.
if [[ "$choice" == "quit" ]]; then
    echo "Program terminated." && exit 0

# What to do when/if we choose a file to edit.
elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	$DMENUEDITOR $cfg

# What to do if we just escape without choosing anything.
else
    echo "Program terminated." && exit 0
fi
