#!/usr/bin/sh
#
# Nom de l'script: dmhistory
# Descripció: per executar una ordre de l'historial.
# Dependències: dmenu
# Llicència: https://www.github.com/enricg/scripts/LICENSE
# Contributors:
# Author: Enric Giner

# Definició de l'editor de text a utilitzar.
DMENUEDITOR="alacritty -e $EDITOR"

# La llista d'opcions per escollir.
#source ~/.cache/zsh/history
# Llista de l'historial

#history | dmenu -l 30

historial=$(fc -l -50)
echo $historial

#llista="llista1\nllista2\nllista3"
# Piping the above array into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.

#while [ -z "$choice" ];
#do
##	choice=$(printf '%s\n' "${llista[@]}" | dmenu -i -l 30 -p "Tria l'ordre de l'historial:") || exit
#	choice=$(printf '%s\n' "${llista[@]}" | dmenu -i -l 30 -p "Tria l'ordre de l'historial::") || exit
#done

#choice=$(echo $items | dmenu -i -l 30)
#choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l 20 -p 'Edit config:')

# What to do when/if we choose 'quit'.
#if [[ "$choice" == "quit" ]]; then
#    echo "Program terminated." && exit 0
#
## What to do when/if we choose a file to edit.
#elif [ "$choice" ]; then
#	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
#	$DMENUEDITOR $cfg
#
## What to do if we just escape without choosing anything.
#else
#    echo "Program finalitzat." && exit 0
#fi
