#!/usr/bin/env bash
# Script per a poder afegir notes o crear-ne de noves d'una manera ràpida"

notes_path="$HOME/Documents/Notes"

#edit="$EDITOR"
EDITOR="nvim" # Ho afegeixo perquè el dmenu no m'agafa les variables d'entorn
DMENUEDITOR="alacritty -e $EDITOR"

prompt="-p "

list="$(find -L $notes_path -maxdepth 1 -type f \
       | sed 's|^'$notes_path/'||' \
       | sort \
       )"

select="$(echo -e "$list" | dmenu $prompt $font $colors $lines)"

slugger () {
echo $@ | tr -d '[:punct:]'     \
        | sed -e "s/ /-/g"      \
              -e "s/[áàãâ]/a/g" \
              -e "s/[éê]/e/g"   \
              -e "s/[íÍ]/i/g"   \
              -e "s/[óõô]/o/g"  \
              -e "s/[úü]/u/g"   \
              -e "s/[ç]/c/g"
}

create_note () {
    filename="$(slugger "${1,,}")"
    note="$notes_path/$filename.md"
    title="${1,,}"
    echo -e "# ${title^}\n\n" > "$note"
    notify-send -i "notes" "Nova nota!" "La nota <b>$filename.md</b> s'ha creat a  '$notes_path'"
}

open_note () {
    note_select="$notes_path/$select"
    if [[ ! -f "$note_select" ]]; then
        create_note "$select"
    else
        note="$note_select"
    fi
    $DMENUEDITOR $note
}

if [[ ! -z "$select" ]]; then
    open_note
fi

exit 0
