#!/bin/bash

#--------------------------------------------------------------------
# Clona tots els repositoris de github.com d'un usuari específic
#
# Us:
# download-all-repos <nom_usuari>
#--------------------------------------------------------------------

if [ $# -eq 0 ]
  then
    echo "Usage: $0 <user_name> "
    exit;
fi

USER=$1
mkdir $1 && cd $1

for repo in `curl -s https://api.github.com/users/$USER/repos?per_page=1000 |grep git_url |awk '{print $2}'| sed 's/"\(.*\)",/\1/'`;do
git clone $repo;
done;
