#!/bin/bash

if [ $# -eq 1 ]
then
directori=$1
find $1 -mindepth 1 -type d -printf '%p %f\n' | sort -t ' ' -k 2,2 | uniq -f 1 --all-repeated=separate | cut -d' ' -f1
else
	echo "has de passar la carpeta d'inici. Per exemple, ./"
fi
