#!/bin/sh

! echo "$1" | grep "https*://\S\+\.[A-Za-z]\+\S*" >/dev/null &&
# ! echo "$1" | grep "https*:\/\/\S*\bblog|feed|rss|news|xml*" >/dev/null &&
	notify-send "That doesn't look like a full URL." && exit
	RSSFILE="${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/urls"
	if awk '{print $1}' "$RSSFILE" | grep "^$1$" >/dev/null; then
		notify-send "You already have this RSS feed."
	else
		echo "$1" >> "$RSSFILE" && notify-send "RSS feed added."
		sort -o $RSSFILE $RSSFILE
	fi
