#!/bin/sh

CATEGORIA=""

! echo "$1" | grep "https*://\S\+\.[A-Za-z]\+\S*" >/dev/null &&
	# ! echo "$1" | grep "https*:\/\/\S*\bblog|feed|rss|news|xml*" >/dev/null &&
	notify-send "Això no sembla un URL correcte." && exit
	RSSFILE="${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/urls"
	if awk '{print $1}' "$RSSFILE" | grep "^$1$" >/dev/null; then
		notify-send "Aquest canal RSS ja existeix."
	else
		case $1 in
			*"youtube"*)
				CATEGORIA='"youtube"'
				;;
		esac

		echo "$1 $CATEGORIA" >> "$RSSFILE" && notify-send "S'ha afegit un feed RSS."
		sort -o $RSSFILE $RSSFILE
	fi
